### ISSUE TITLE
panel>1 jstree not doing anything when called on div id 

### ISSUE THREAD

**Issue by madeline-scyphers** [madeline-scyphers/panel-jstree#2]
working branch - https://github.com/madeline-scyphers/panel-jstree/tree/feature/panel-1.0

Having problems getting this to render in panel>1/bokeh>3 this works fine in panel<1/bokeh<3 (as long as you change the
HTMLBox and HTMLBoxView import from bokeh in panel<1 to from layout.ts in panel>1 the jstree.ts file. There are comments in jstree.ts that say which imports are for which version. And you have to change the package.json file to say panel and bokeh have to be the right versions).

In panel>1 you can still get jstree to work by running the jQuery in the browser console directly on different div id. I don't know if in bokeh>3 it is putting things in elements and that is interfering with jstree, or something else.

Once the app is running, in your browser by entering (replace id-of-div with the id of your div):
```javascript
jQuery('#`id-of-div`').jstree({ 'core' : {
        'data' : [
           'Simple root node',
           {
             'text' : 'Root node 2',
             'state' : {
               'opened' : true,
               'selected' : true
             },
             'children' : [
               { 'text' : 'Child 1' },
               'Child 2'
             ]
          }
        ]
    } });
```

If you inspect the original raw html, you will see that the div that jstree.ts created didn't get the list added to it is was supposed to at all, so the the jstree constructor didn't work, but it does when applying to divs that aren't the one bokeh provides for jstree. At least it does for the outermost ones. I am not sure if it does for all of them or not. More testing required. It seems like the elements from bokeh now are shadow elements? It seems like maybe those are the ones that jstree won't attach too maybe?

**Comment by philippjfr** [comment]
Just a quick note that I haven't forgotten about this and will contribute the updates as soon as I get a spare minute and will then try to distill the required changes into a migration guide.

**Comment by madeline-scyphers** [comment]
@philippjfr would it be easier if I put in a draft PR into panel for jstree to be added? That is my ultimate goal anyways, and that way it can be worked on in panel instead of as an external extension.

**Comment by philippjfr** [comment]
Sorry I haven't made progress here, I did start playing around with this. Let me spend another 20 minutes now and then push up a PR.

**Comment by philippjfr** [comment]
PR here: https://github.com/madeline-scyphers/panel-jstree/pull/3
